authapp/urls.py
from django.urls import path

from authapp.views import UserLoginView, UserCreateView, UserUpdateView, UserLogoutView

app_name = 'authapp'
urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('profile/<int:pk>', UserUpdateView.as_view(), name='profile'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('verify/<str:email>/<str:activation_key>', UserCreateView.verify, name='verify')
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

from mainapp.views import IndexTemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexTemplateView.as_view(), name='index'),
    path('products/', include('mainapp.urls', namespace='mainapp')),
    path('users/', include('authapp.urls', namespace='authapp')),
    path('basket/', include('basketapp.urls', namespace='basketapp')),
    path('admins/', include('adminapp.urls', namespace='adminapp')),
    path('', include('social_django.urls', namespace='social')),
    path('orders/', include('ordersapp.urls', namespace='ordersapp')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path(r'^__debug__/', include(debug_toolbar.urls)),
    ]

mainapp/urls.py
from django.urls import path

from mainapp.views import ProductsListView, ProductDetailView

app_name = 'mainapp'
urlpatterns = [
    path('', ProductsListView.as_view(), name='products'),
    path('category/<int:category_pk>', ProductsListView.as_view(), name='category'),
    path('page/<int:page_number>', ProductsListView.as_view(), name='page'),
    path('category/<int:category_pk>/page/<int:page_number>', ProductsListView.as_view(), name='category_by_page'),
    path('<int:pk>/', ProductDetailView.as_view(), name='detail'),
]

mainapp/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)
    desc = models.TextField(blank=True, null=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=128)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    desc = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='product_img', blank=True)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.name} | {self.category}'

mainapp/views.py
from django.core.paginator import Paginator
from django.views.generic import TemplateView, ListView, DetailView

from .models import Product, Category


class IndexTemplateView(TemplateView):
    template_name = 'mainapp/index.html'
    extra_context = {'title': 'GeekShop'}


class ProductsListView(ListView):
    model = Product
    queryset = Product.objects.filter(is_active=True, quantity__gt=0)
    category_pk = None
    template_name = 'mainapp/products.html'
    context_object_name = 'products'
    paginate_by = 6
    page_kwarg = 'page_number'

    def get_context_data(self, **kwargs):
        self.category_pk = self.kwargs.get('category_pk')
        title = 'GeekShop - Каталог'
        if self.category_pk:
            self.queryset = Product.objects.filter(is_active=True, category=self.category_pk, quantity__gt=0)
            title = f'GeekShop - Каталог|{Category.objects.get(pk=self.category_pk).name}'

        context = super(ProductsListView, self).get_context_data(object_list=self.queryset, **kwargs)
        if self.paginate_by:
            current_page = context['page_obj'].number
            page_range = context['paginator'].get_elided_page_range(current_page)
        else:
            current_page = None
            page_range = None

        context.update({
            'title': title,
            'current_category': self.category_pk,
            'categories': Category.objects.filter(is_active=True),
            'page_range': page_range
        })
        return context


class ProductDetailView(DetailView):
    model = Product
    template_name = 'mainapp/detail.html'
    extra_context = {}

    def get_context_data(self, **kwargs):
        self.extra_context.update({'title': f'GeekShop - {self.object.name}'})
        return super(ProductDetailView, self).get_context_data(**kwargs)

mainapp/templates/mainapp/includes/inc_footer.html
{% block footer %}
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; GeekShop 2021</p>
        </div>
        <!-- /.container -->
    </footer>
{% endblock %}

mainapp/templates/mainapp/includes/inc_pagination.html
{% if is_paginated %}
    <ul class="pagination justify-content-center flex-wrap mt-2 mb-4">
        {% if page_obj.has_previous %}
            <li class="page-item">
                {% if current_category %}
                    <a class="page-link"
                       href="{% url 'mainapp:category_by_page' current_category page_obj.previous_page_number %}">Previous</a>
                {% else %}
                    <a class="page-link"
                       href="{% url 'mainapp:page' page_obj.previous_page_number %}">Previous</a>
                {% endif %}
            </li>

        {% else %}
            <li class="disabled page-item"><span class="page-link">Previous</span></li>
        {% endif %}

        {% for i in page_range %}
            {% if page_obj.number == i %}
                <li class="active page-item">
                    <span class="page-link">{{ i }}
                        <span class="sr-only">(current)</span>
                    </span>
                </li>
            {% else %}
                {% if i == page_obj.paginator.ELLIPSIS %}
                    <li class="page-item"><span class="page-link">{{ i }}</span></li>
                {% else %}
                    {% if current_category %}
                        <li class="page-item">
                            <a class="page-link"
                               href="{% url 'mainapp:category_by_page' current_category i %}">{{ i }}</a>
                        </li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="{% url 'mainapp:page' i %}">{{ i }}</a></li>
                    {% endif %}
                {% endif %}
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item">
                {% if current_category %}
                    <a class="page-link"
                       href="{% url 'mainapp:category_by_page' current_category page_obj.next_page_number %}">Next</a>
                {% else %}
                    <a class="page-link"
                       href="{% url 'mainapp:page' page_obj.next_page_number %}">Next</a>
                {% endif %}
            </li>
        {% else %}
            <li class="disabled page-item"><span class="page-link">Next</span></li>
        {% endif %}
    </ul>
{% endif %}