adminapp/urls.py
from django.urls import path

from adminapp.views import AdminTemplateView, \
    AdminUsersListView, AdminUserCreateView, AdminUserUpdateView, AdminUserDeleteView, \
    AdminCategoriesListView, AdminCategoryCreateView, AdminCategoryUpdateView, AdminCategoryDeleteView, \
    AdminProductCreateView, AdminProductsListView, AdminProductUpdateView, AdminProductDeleteView

app_name = 'adminapp'

urlpatterns = [
    path('', AdminTemplateView.as_view(), name='index'),
    path('user_create/', AdminUserCreateView.as_view(), name='user_create'),
    path('users/', AdminUsersListView.as_view(), name='users'),
    path('user_update/<int:pk>', AdminUserUpdateView.as_view(), name='user_update'),
    path('user_delete/<int:pk>', AdminUserDeleteView.as_view(), name='user_delete'),
    path('category_create/', AdminCategoryCreateView.as_view(), name='category_create'),
    path('categories/', AdminCategoriesListView.as_view(), name='categories'),
    path('category_update/<int:pk>', AdminCategoryUpdateView.as_view(), name='category_update'),
    path('category_delete/<int:pk>', AdminCategoryDeleteView.as_view(), name='category_delete'),
    path('product_create/', AdminProductCreateView.as_view(), name='product_create'),
    path('products/', AdminProductsListView.as_view(), name='products'),
    path('product_update/<int:pk>', AdminProductUpdateView.as_view(), name='product_update'),
    path('product_delete/<int:pk>', AdminProductDeleteView.as_view(), name='product_delete'),
]

authapp/urls.py
from django.urls import path

from authapp.views import UserLoginView, UserCreateView, UserUpdateView, UserLogoutView

app_name = 'authapp'
urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('profile/<int:pk>', UserUpdateView.as_view(), name='profile'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('verify/<str:email>/<str:activation_key>', UserCreateView.verify, name='verify')
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

from mainapp.views import IndexTemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexTemplateView.as_view(), name='index'),
    path('products/', include('mainapp.urls', namespace='mainapp')),
    path('users/', include('authapp.urls', namespace='authapp')),
    path('basket/', include('basketapp.urls', namespace='basketapp')),
    path('admins/', include('adminapp.urls', namespace='adminapp')),
    path('', include('social_django.urls', namespace='social')),
    path('orders/', include('ordersapp.urls', namespace='ordersapp')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path(r'^__debug__/', include(debug_toolbar.urls)),
    ]

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django import forms

from authapp.forms import UserRegisterForm, UserProfileForm
from authapp.models import User
from authapp.validate import validate_age
from mainapp.models import Category, Product


def update_widgets(fields):
    labels = {
        'name': 'Наименование',
        'desc': 'Описание',
        'price': 'Цена',
        'image': 'Изображение',
        'quantity': 'Количество',
        'category': 'Категория',
    }

    placeholders = {
        'name': 'Введите наименование',
        'desc': 'Введите описание',
        'price': 'Введите цену',
        'image': 'Загрузите изображение',
        'quantity': 'Введите количество',
        'category': 'Выберите категорию',
    }

    for name, field in fields.items():
        if name == 'image':
            field.widget.attrs['class'] = 'custom-file-input'
        else:
            field.widget.attrs['class'] = 'form-control'
        if name in labels:
            field.label = labels[name]
        if name in placeholders:
            field.widget.attrs['placeholder'] = placeholders[name]


class UserCreateForm(UserRegisterForm):
    image = forms.ImageField(widget=forms.FileInput, required=False)
    age = forms.IntegerField(widget=forms.NumberInput, validators=[validate_age])

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'image',
            'age',
            'username',
            'email',
            'password1',
            'password2',
        )


class UserUpdateForm(UserProfileForm):
    def __init__(self, *args, **kwargs):
        super(UserUpdateForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['readonly'] = False
        self.fields['email'].widget.attrs['readonly'] = False


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name', 'desc')

    def __init__(self, *args, **kwargs):
        super(CategoryForm, self).__init__(*args, **kwargs)
        update_widgets(self.fields)
        self.fields['name'].widget.attrs['autofocus'] = True


class ProductForm(forms.ModelForm):
    image = forms.ImageField(widget=forms.FileInput, required=False)

    class Meta:
        model = Product
        fields = ('name', 'price', 'desc', 'image', 'quantity', 'category')

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        self.fields['category'] = forms.ModelChoiceField(queryset=Category.objects.filter(is_active=True))
        update_widgets(self.fields)
        self.fields['name'].widget.attrs['autofocus'] = True

adminapp/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DeleteView

from adminapp.forms import UserCreateForm, UserUpdateForm, CategoryForm, ProductForm
from authapp.models import User
from adminapp.mixins import ProtectDispatchMixin, AdminDeleteMixin
from mainapp.models import Category, Product

titles = {
    'admin_index': 'Geekshop - Админ.панель',
    'admin_user': {
        'create': 'Geekshop - Админ.панель|Пользователи-добавление',
        'read': 'Geekshop - Админ.панель|Пользователи',
        'update': 'Geekshop - Админ.панель|Пользователи-обновление',
    },
    'admin_category': {
        'create': 'Geekshop - Админ.панель|Категории-добавление',
        'read': 'Geekshop - Админ.панель|Категории',
        'update': 'Geekshop - Админ.панель|Категории-обновление',
    },
    'admin_product': {
        'create': 'Geekshop - Админ.панель|Товары-добавление',
        'read': 'Geekshop - Админ.панель|Товары',
        'update': 'Geekshop - Админ.панель|Товары-обновление',
    },
}

success_messages = {
    'create': 'Данные успешно добавлены',
    'update': 'Данные успешно обновлены',
}


# Главная страница админки
class AdminTemplateView(ProtectDispatchMixin, TemplateView):
    extra_context = {'title': titles['admin_index']}
    template_name = 'adminapp/main.html'


# Отображение пользователей
class AdminUsersListView(ProtectDispatchMixin, ListView):
    model = User
    extra_context = {'title': titles['admin_user'].get('read')}
    context_object_name = 'users'
    template_name = 'adminapp/users.html'


class AdminUserCreateView(SuccessMessageMixin, ProtectDispatchMixin, CreateView):
    model = User
    form_class = UserCreateForm
    extra_context = {'title': titles['admin_user'].get('create')}
    template_name = 'adminapp/user_create.html'
    success_url = reverse_lazy('adminapp:users')
    success_message = success_messages['create']


class AdminUserUpdateView(SuccessMessageMixin, ProtectDispatchMixin, UpdateView):
    model = User
    form_class = UserUpdateForm
    extra_context = {'title': titles['admin_user'].get('update')}
    template_name = 'adminapp/user_update_delete.html'
    success_url = reverse_lazy('adminapp:users')
    success_message = success_messages['update']


class AdminUserDeleteView(SuccessMessageMixin, ProtectDispatchMixin, AdminDeleteMixin, DeleteView):
    model = User
    success_url = reverse_lazy('adminapp:users')


# Отображение категорий товаров
class AdminCategoriesListView(ProtectDispatchMixin, ListView):
    model = Category
    context_object_name = 'categories'
    extra_context = {'title': titles['admin_category'].get('read')}
    template_name = 'adminapp/categories.html'


class AdminCategoryCreateView(SuccessMessageMixin, ProtectDispatchMixin, CreateView):
    model = Category
    form_class = CategoryForm
    extra_context = {'title': titles['admin_category'].get('create')}
    template_name = 'adminapp/category_create.html'
    success_url = reverse_lazy('adminapp:categories')
    success_message = success_messages['create']


class AdminCategoryUpdateView(SuccessMessageMixin, ProtectDispatchMixin, UpdateView):
    model = Category
    form_class = CategoryForm
    extra_context = {'title': titles['admin_category'].get('update')}
    template_name = 'adminapp/category_update_delete.html'
    success_url = reverse_lazy('adminapp:categories')
    success_message = success_messages['update']


class AdminCategoryDeleteView(SuccessMessageMixin, ProtectDispatchMixin, AdminDeleteMixin, DeleteView):
    model = Category
    success_url = reverse_lazy('adminapp:categories')


# Отображение товаров
class AdminProductsListView(ProtectDispatchMixin, ListView):
    model = Product
    context_object_name = 'products'
    extra_context = {'title': titles['admin_product'].get('read')}
    template_name = 'adminapp/products.html'

    def get_queryset(self):
        return Product.objects.select_related()


class AdminProductCreateView(SuccessMessageMixin, ProtectDispatchMixin, CreateView):
    model = Product
    form_class = ProductForm
    extra_context = {'title': titles['admin_product'].get('create')}
    template_name = 'adminapp/product_create.html'
    success_url = reverse_lazy('adminapp:products')
    success_message = success_messages['create']


class AdminProductUpdateView(SuccessMessageMixin, ProtectDispatchMixin, UpdateView):
    model = Product
    form_class = ProductForm
    extra_context = {'title': titles['admin_product'].get('update')}
    template_name = 'adminapp/product_update_delete.html'
    success_url = reverse_lazy('adminapp:products')
    success_message = success_messages['update']


class AdminProductDeleteView(SuccessMessageMixin, ProtectDispatchMixin, AdminDeleteMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('adminapp:products')

adminapp/templates/adminapp/admin-users-read.html
{% extends 'adminapp/base.html' %}
{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Пользователи</h1>
                {% include 'authapp/includes/inc_message.html' %}
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        Пользователи
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Имя пользователя</th>
                                    <th>Имя</th>
                                    <th>Фамилия</th>
                                    <th>Адрес эл. почты</th>
                                    <th>Персонал сайта</th>
                                    <th>Активный</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for user in users %}
                                    <tr class="{% if not user.is_active %} non_active {% endif %}">
                                        <td><a href="{% url 'adminapp:user_update' user.id %}"
                                               style="color: dodgerblue">{{ user.username }}</a></td>
                                        <td>{{ user.first_name }}</td>
                                        <td>{{ user.last_name }}</td>
                                        <td>{{ user.email }}</td>
                                        <td class="text-center">
                                            {% if user.is_staff %}
                                                <i class="fas fa-check-circle"></i>
                                            {% else %}
                                                <i class="fas fa-times-circle"></i>
                                            {% endif %}
                                        </td>
                                        <td class="text-center">
                                            {% if user.is_active %}
                                                <i class="fas fa-check-circle"></i>
                                            {% else %}
                                                <i class="fas fa-times-circle"></i>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'adminapp:user_create' %}"
                           class="btn btn-success">
                            Создать пользователя
                        </a>
                    </div>
                </div>
            </div>
        </main>
        {% include 'adminapp/includes/inc_footer.html' %}
    </div>
{% endblock %}

adminapp/templates/adminapp/admin-users-update-delete.html
{% extends 'adminapp/base.html' %}
{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Редактирование пользователя - {{ user.username }}</h1>
                {% include 'authapp/includes/inc_message.html' %}
                <div class="card-body">
                    <form action="{% url 'adminapp:user_update' user.id %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col-lg-5">
                                <div class="form-group">
                                    <label class="small mb-1"
                                           for="{{ form.first_name.id_for_label }}">{{ form.first_name.label }}</label>
                                    {{ form.first_name }}
                                </div>
                            </div>
                            <div class="col-lg-5">
                                <div class="form-group">
                                    <label class="small mb-1"
                                           for="{{ form.last_name.id_for_label }}">{{ form.last_name.label }}</label>
                                    {{ form.last_name }}
                                </div>
                            </div>
                            <div class="col-lg-2">
                                <div class="form-group">
                                    <label class="small mb-1"
                                           for="{{ form.age.id_for_label }}">{{ form.age.label }}</label>
                                    {{ form.age }}
                                </div>
                            </div>
                        </div>
                        <div class="form-row mb-2">
                            <div class="col-lg-12">
                                <div class="custom-file">
                                    {{ form.image }}
                                    <label class="custom-file-label"
                                           for="{{ form.image.id_for_label }}">{{ form.image.label }}</label>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-6">
                                <label class="small mb-1"
                                       for="{{ form.username.id_for_label }}">{{ form.username.label }}</label>
                                {{ form.username }}
                            </div>
                            <div class="col-lg-6">
                                <label class="small mb-1"
                                       for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
                                {{ form.email }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-12" style="margin-top: 33px;">
                                <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                            </div>
                        </div>
                    </form>

                    <form action="{% url 'adminapp:user_delete' user.id %}" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-lg-12" style="margin-top: 33px;">
                                <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </main>
        {% include 'adminapp/includes/inc_footer.html' %}
    </div>
{% endblock %}

adminapp/templates/adminapp/admin.html
{% extends 'adminapp/base.html' %}
{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Административная панель</h1>

            </div>
        </main>
        {% include 'adminapp/includes/inc_footer.html' %}
    </div>
{% endblock %}

adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Категории товаров</h1>
                {% include 'authapp/includes/inc_message.html' %}
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        Категории товаров
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Имя категории</th>
                                    <th>Описание</th>
                                    <th>Активная</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for category in categories %}
                                    <tr class="{% if not category.is_active %} non_active {% endif %}">
                                        <td><a href="{% url 'adminapp:category_update' category.id %}"
                                               style="color: dodgerblue">{{ category.name }}</a></td>
                                        <td>{{ category.desc }}</td>
                                        <td class="text-center">
                                            {% if category.is_active %}
                                                <i class="fas fa-check-circle"></i>
                                            {% else %}
                                                <i class="fas fa-times-circle"></i>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'adminapp:category_create' %}"
                           class="btn btn-success">
                            Создать категорию
                        </a>
                    </div>
                </div>
            </div>
        </main>
        {% include 'adminapp/includes/inc_footer.html' %}
    </div>
{% endblock %}

adminapp/templates/adminapp/category_update_delete.html
{% extends 'adminapp/base.html' %}
{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Редактирование категории - "{{ category.name }}"</h1>
                {% include 'authapp/includes/inc_message.html' %}
                <div class="card-body">
                    <form action="{% url 'adminapp:category_update' category.id %}" method="post">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label class="small mb-1"
                                           for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
                                    {{ form.name }}
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label class="small mb-1"
                                           for="{{ form.desc.id_for_label }}">{{ form.desc.label }}</label>
                                    {{ form.desc }}
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-12" style="margin-top: 33px;">
                                <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                            </div>
                        </div>
                    </form>

                    <form action="{% url 'adminapp:category_delete' category.id %}" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-lg-12" style="margin-top: 33px;">
                                <input class="btn btn-block {% if category.is_active %}btn-danger{% else %}btn-success{% endif %}"
                                       type="submit" value="{% if category.is_active %}Удалить{% else %}Восстановить{% endif %}">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </main>
        {% include 'adminapp/includes/inc_footer.html' %}
    </div>
{% endblock %}

adminapp/templates/adminapp/main.html
{% extends 'adminapp/base.html' %}
{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Административная панель</h1>

            </div>
        </main>
        {% include 'adminapp/includes/inc_footer.html' %}
    </div>
{% endblock %}

adminapp/templates/adminapp/product_update_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Редактирование товара - "{{ product.name }}"</h1>
                {% include 'authapp/includes/inc_message.html' %}
                <div class="card-body">
                    <form action="{% url 'adminapp:product_update' product.id %}" method="post"
                          enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col-lg-5">
                                <div class="form-group">
                                    <label class="small mb-1"
                                           for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
                                    {{ form.name }}
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label class="small mb-1"
                                           for="{{ form.category.id_for_label }}">{{ form.category.label }}</label>
                                    {{ form.category }}
                                </div>
                            </div>
                            <div class="col-lg-2">
                                <div class="form-group">
                                    <label class="small mb-1"
                                           for="{{ form.price.id_for_label }}">{{ form.price.label }}</label>
                                    {{ form.price }}
                                </div>
                            </div>
                            <div class="col-lg-2">
                                <div class="form-group">
                                    <label class="small mb-1"
                                           for="{{ form.quantity.id_for_label }}">{{ form.quantity.label }}</label>
                                    {{ form.quantity }}
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label class="small mb-1"
                                           for="{{ form.desc.id_for_label }}">{{ form.desc.label }}</label>
                                    {{ form.desc }}
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-1" id="img_preview">
                                <img width="100" height="100"
                                     src="{% if product.image %} {{ form.initial.image.url }} {% else %} {% static 'vendor/img/products/default.jpg' %} {% endif %}"
                                     class=" img-thumbnail">
                            </div>
                            <div class="col-lg-11">
                                <div class="form-group">
                                    {{ form.image }}
                                    <label class="custom-file-label"
                                           for="{{ form.image.id_for_label }}">{{ form.image.label }}</label>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-12" style="margin-top: 33px;">
                                <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                            </div>
                        </div>
                    </form>

                    <form action="{% url 'adminapp:product_delete' product.id %}" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-lg-12" style="margin-top: 33px;">
                                <input class="btn btn-block {% if product.is_active %}btn-danger{% else %}btn-success{% endif %}"
                                       type="submit" value="{% if product.is_active %}Удалить{% else %}Восстановить{% endif %}">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </main>
        {% include 'adminapp/includes/inc_footer.html' %}
    </div>
{% endblock %}

adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Товары</h1>
                {% include 'authapp/includes/inc_message.html' %}
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        Товары
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Наименование товара</th>
                                    <th>Цена</th>
                                    <th>Описание</th>
                                    <th>Изображение</th>
                                    <th>Количество</th>
                                    <th>Категория</th>
                                    <th>Активный</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for product in products %}
                                    <tr class="{% if not product.is_active %} non_active {% endif %}">
                                        <td><a href="{% url 'adminapp:product_update' product.id %}"
                                               style="color: dodgerblue">{{ product.name }}</a></td>
                                        <td>{{ product.price }}</td>
                                        <td>{{ product.desc }}</td>
                                        <td>{{ product.image }}</td>
                                        <td>{{ product.quantity }}</td>
                                        <td>{{ product.category }}</td>
                                        <td class="text-center">
                                            {% if product.is_active %}
                                                <i class="fas fa-check-circle"></i>
                                            {% else %}
                                                <i class="fas fa-times-circle"></i>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'adminapp:product_create' %}"
                           class="btn btn-success">
                            Создать товар
                        </a>
                    </div>
                </div>
            </div>
        </main>
        {% include 'adminapp/includes/inc_footer.html' %}
    </div>
{% endblock %}