authapp/urls.py
from django.urls import path

from authapp.views import UserLoginView, UserCreateView, UserUpdateView, UserLogoutView

app_name = 'authapp'
urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('profile/<int:pk>', UserUpdateView.as_view(), name='profile'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('verify/<str:email>/<str:activation_key>', UserCreateView.verify, name='verify')
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

from mainapp.views import IndexTemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexTemplateView.as_view(), name='index'),
    path('products/', include('mainapp.urls', namespace='mainapp')),
    path('users/', include('authapp.urls', namespace='authapp')),
    path('basket/', include('basketapp.urls', namespace='basketapp')),
    path('admins/', include('adminapp.urls', namespace='adminapp')),
    path('', include('social_django.urls', namespace='social')),
    path('orders/', include('ordersapp.urls', namespace='ordersapp')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path(r'^__debug__/', include(debug_toolbar.urls)),
    ]

mainapp/urls.py
from django.urls import path

from mainapp.views import ProductsListView, ProductDetailView

app_name = 'mainapp'
urlpatterns = [
    path('', ProductsListView.as_view(), name='products'),
    path('category/<int:category_pk>', ProductsListView.as_view(), name='category'),
    path('page/<int:page_number>', ProductsListView.as_view(), name='page'),
    path('category/<int:category_pk>/page/<int:page_number>', ProductsListView.as_view(), name='category_by_page'),
    path('<int:pk>/', ProductDetailView.as_view(), name='detail'),
]

ordersapp/urls.py
from django.urls import path

from ordersapp.views import OrderList, OrderCreateView, OrderUpdateView, OrderDeleteView, OrderDetailView, \
    order_forming_complete

app_name = 'ordersapp'
urlpatterns = [
    path('', OrderList.as_view(), name='list'),
    path('create/', OrderCreateView.as_view(), name='create'),
    path('update/<int:pk>', OrderUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', OrderDeleteView.as_view(), name='delete'),
    path('read/<int:pk>', OrderDetailView.as_view(), name='read'),
    path('forming_complete/<int:pk>', order_forming_complete, name='forming_complete'),
]

mainapp/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)
    desc = models.TextField(blank=True, null=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=128)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    desc = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='product_img', blank=True)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.name} | {self.category}'

mainapp/views.py
from django.core.paginator import Paginator
from django.views.generic import TemplateView, ListView, DetailView

from .models import Product, Category


class IndexTemplateView(TemplateView):
    template_name = 'mainapp/index.html'
    extra_context = {'title': 'GeekShop'}


class ProductsListView(ListView):
    model = Product
    queryset = Product.objects.filter(is_active=True, quantity__gt=0)
    category_pk = None
    template_name = 'mainapp/products.html'
    context_object_name = 'products'
    paginate_by = 6
    page_kwarg = 'page_number'

    def get_context_data(self, **kwargs):
        self.category_pk = self.kwargs.get('category_pk')
        title = 'GeekShop - Каталог'
        if self.category_pk:
            self.queryset = Product.objects.filter(is_active=True, category=self.category_pk, quantity__gt=0)
            title = f'GeekShop - Каталог|{Category.objects.get(pk=self.category_pk).name}'

        context = super(ProductsListView, self).get_context_data(object_list=self.queryset, **kwargs)
        if self.paginate_by:
            current_page = context['page_obj'].number
            page_range = context['paginator'].get_elided_page_range(current_page)
        else:
            current_page = None
            page_range = None

        context.update({
            'title': title,
            'current_category': self.category_pk,
            'categories': Category.objects.filter(is_active=True),
            'page_range': page_range
        })
        return context


class ProductDetailView(DetailView):
    model = Product
    template_name = 'mainapp/detail.html'
    extra_context = {}

    def get_context_data(self, **kwargs):
        self.extra_context.update({'title': f'GeekShop - {self.object.name}'})
        return super(ProductDetailView, self).get_context_data(**kwargs)

mainapp/templates/mainapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static  'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block css %}{% endblock %}

</head>
<body>
<div class="main_wrapper">
    <!-- Navigation -->
    <div class="main_wrapper__top">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container">
                <a class="navbar-brand" href={% url 'index' %}>GeekShop - {% now 'jS F Y' %}</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                        aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href={% url 'mainapp:products' %}>Каталог <i
                                    class="fas fa-shopping-bag"></i>
                            </a>
                        </li>
                        {% if not user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'authapp:login' %}">Войти <i
                                        class="fas fa-sign-in-alt"></i></a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <div class="dropdown">
                                    <a href="" class="nav-link dropdown-toggle" data-toggle="dropdown">
                                        {{ user.username|title }}
                                        <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <a href="{% url 'authapp:profile' user.id %}" class="nav-link text-dark">
                                                Профиль
                                            </a>
                                        </li>
                                        <li>
                                            <a href="{% url 'ordersapp:list' %}" class="nav-link text-dark">
                                                Заказы
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </li>
                            {% if user.is_superuser %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'adminapp:index' %}">
                                        <i class="fas fa-users-cog"></i>
                                    </a>
                                </li>
                            {% endif %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'authapp:logout' %}">Выйти <i
                                        class="fas fa-sign-out-alt"></i></a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        <!-- Page Content -->
        {% block content %}{% endblock %}
    </div>

    <div class="main__wrapper__bottom">
        <!-- Footer Content -->
        {% block footer %}{% endblock %}
    </div>
</div>

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/basket.js' %}"></script>
<script src="{% static 'js/img_preview.js' %}"></script>
<script src="{% static 'js/order.js' %}"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

</body>
</html>

mainapp/templates/mainapp/detail.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <h1 class="my-4">GeekShop</h1>
                <div class="list-group">
                    <a href="{% url 'mainapp:products' %}" class="list-group-item">Все</a>
                </div>
            </div>

            <div class="col-lg-9">
                <div class="row my-5">
                    <div class="card" style="width: 20rem;">
                        <img src="{{ product.image.url }}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{ product.name }}</h5>
                            <p class="card-text">{{ product.desc }}</p>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">{{ product.price }} руб</li>
                            <li class="list-group-item">В наличии: {{ product.quantity }}</li>
                        </ul>
                        <div class="card-footer text-center">
                            <a
                                    id="add_basket"
                                    data-id="{{ product.id }}"
                                    class="btn btn-outline-success">Отправить в корзину
                            </a>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block footer %}
    {% include 'mainapp/includes/inc_footer.html' %}
{% endblock %}

mainapp/templates/mainapp/footer.html
{% block footer %}
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; GeekShop 2021</p>
        </div>
        <!-- /.container -->
    </footer>
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h1 class="mt-5">GeekShop Store</h1>
                    <p>
                        Новые образы и лучшие бренды на GeekShop Store.
                        Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                    </p>
                    <button id="start-purchase-btn" type="button" class="btn btn-lg">
                        <a id="start-purchase-link" href={% url 'mainapp:products' %}>
                            Начать покупки
                        </a>
                    </button>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'css/products.css' %}" rel="stylesheet">
{% endblock %}

<!-- Page Content -->
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <h1 class="my-4">GeekShop</h1>
                <div class="list-group">
                    <a href="{% url 'mainapp:products' %}"
                       class="list-group-item {% if not current_category %}active{% endif %}">Все товары</a>

                    {% for category in categories %}
                        <a href="{% url 'mainapp:category' category.id %}"
                           class="list-group-item {% if category.id == current_category %}active{% endif %}">{{ category }}</a>
                    {% endfor %}
                </div>

            </div>
            <!-- /.col-lg-3 -->
            <div class="col-lg-9">

                <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-1.jpg' %}"
                                 alt="First slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-2.jpg' %}"
                                 alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-3.jpg' %}"
                                 alt="Third slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
                <div class="row">
                    {% for product in products %}
                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                                <a href="{% url 'mainapp:detail' product.id %}">
                                    <img class="card-img-top"
                                         src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'vendor/img/products/default.jpg' %}{% endif %}"
                                         alt="{{ product.name }}">
                                </a>
                                <div class="card-body">
                                    <h4 class="card-title">
                                        <a href="{% url 'mainapp:detail' product.id %}">{{ product.name }}</a>
                                    </h4>
                                    <h5>{{ product.price }} руб.</h5>
                                    <p class="card-text">{{ product.desc }}</p>
                                </div>
                                <div class="card-footer text-center">
                                    <a
                                            id="add_basket"
                                            data-id="{{ product.id }}"
                                            class="btn btn-outline-success">Отправить в корзину
                                    </a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                </div>
                {% include 'mainapp/includes/inc_pagination.html' %}
            </div>

        </div>

    </div>
    <!-- /.container -->
{% endblock %}
{% block footer %}
    {% include 'mainapp/includes/inc_footer.html' %}
{% endblock %}