authapp/urls.py
from django.urls import path

from authapp.views import UserLoginView, UserCreateView, UserUpdateView, UserLogoutView

app_name = 'authapp'
urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('profile/<int:pk>', UserUpdateView.as_view(), name='profile'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('verify/<str:email>/<str:activation_key>', UserCreateView.verify, name='verify')
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

from mainapp.views import IndexTemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexTemplateView.as_view(), name='index'),
    path('products/', include('mainapp.urls', namespace='mainapp')),
    path('users/', include('authapp.urls', namespace='authapp')),
    path('basket/', include('basketapp.urls', namespace='basketapp')),
    path('admins/', include('adminapp.urls', namespace='adminapp')),
    path('', include('social_django.urls', namespace='social')),
    path('orders/', include('ordersapp.urls', namespace='ordersapp')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path(r'^__debug__/', include(debug_toolbar.urls)),
    ]

ordersapp/urls.py
from django.urls import path

from ordersapp.views import OrderList, OrderCreateView, OrderUpdateView, OrderDeleteView, OrderDetailView, \
    order_forming_complete

app_name = 'ordersapp'
urlpatterns = [
    path('', OrderList.as_view(), name='list'),
    path('create/', OrderCreateView.as_view(), name='create'),
    path('update/<int:pk>', OrderUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', OrderDeleteView.as_view(), name='delete'),
    path('read/<int:pk>', OrderDetailView.as_view(), name='read'),
    path('forming_complete/<int:pk>', order_forming_complete, name='forming_complete'),
]

ordersapp/models.py
from django.conf import settings
from django.db import models, transaction

# Create your models here.
from mainapp.models import Product


class Order(models.Model):
    FORMING = 'FM'
    SEND_TO_PROCEED = 'STP'
    PAID = 'PD'
    PROCESSED = 'PRS'
    READY = 'RDY'
    CANCELED = 'CNL'

    ORDER_STATUS_CHOICES = (
        (FORMING, 'формируется'),
        (SEND_TO_PROCEED, 'отправлен в обработку'),
        (PROCESSED, 'обрабатывается'),
        (PAID, 'оплачен'),
        (READY, 'готов к выдаче'),
        (CANCELED, 'отменен'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(choices=ORDER_STATUS_CHOICES, verbose_name='статус', max_length=3, default=FORMING)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f'Текущий заказ {self.pk}'

    @property
    def total_quantity(self):
        items = self.order_items.select_related()
        return sum(list(map(lambda x: x.quantity, items)))

    @property
    def total_price(self):
        items = self.order_items.select_related()
        return sum(list(map(lambda x: x.total_price, items)))

    def get_items(self):
        pass

    @transaction.atomic
    def delete(self, using=None, keep_parents=False):
        for item in self.order_items.select_related():
            item.product.quantity += item.quantity
            item.save()
        self.is_active = False
        self.save()


class OrderItem(models.Model):
    order = models.ForeignKey(Order, verbose_name='заказ', related_name='order_items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name='товар', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0)

    @property
    def total_price(self):
        return self.product.price * self.quantity

    @staticmethod
    def get_item(pk):
        return OrderItem.objects.get(pk=pk)

    @transaction.atomic
    def save(self, *args, **kwargs):
        if self.pk:
            self.product.quantity -= self.quantity - self.__class__.get_item(self.pk).quantity
        else:
            self.product.quantity -= self.quantity
        self.product.save()
        super(self.__class__, self).save(*args, **kwargs)

ordersapp/forms.py
from django import forms
from django.forms import BaseInlineFormSet

from mainapp.models import Product
from ordersapp.models import Order, OrderItem


class OrderInlineFormSet(BaseInlineFormSet):
    pass


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    # def clean_order_items(self):
    #     data = self.cleaned_data['order_items']
    #     if len(data) == 0:
    #         raise forms.ValidationError("You have forgotten about Fred!")
    #     return data


class OrderItemForm(forms.ModelForm):
    product_id = forms.CharField(widget=forms.HiddenInput)
    product_name = forms.CharField(label='товар', max_length=50)
    price = forms.CharField(label='цена', required=False)

    class Meta:
        model = OrderItem
        fields = ('product_name', 'quantity', 'price')
        exclude = ('product',)

    def __init__(self, *args, **kwargs):
        super(OrderItemForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            if name == 'product_name':
                field.widget.attrs = {'readonly': True, 'size': '70%'}
            field.widget.attrs['class'] = 'form-control'

    def save(self, commit=True):
        self.instance = super(OrderItemForm, self).save(commit=False)
        product_pk = self.cleaned_data['product_id']
        self.instance.product = Product.objects.get(pk=product_pk)
        self.instance.save()
        return self.instance

ordersapp/views.py
# Create your views here.
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db import transaction, IntegrityError
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from basketapp.models import Basket
from ordersapp.forms import OrderItemForm, OrderInlineFormSet
from ordersapp.models import Order, OrderItem


class OrderList(LoginRequiredMixin, ListView):
    model = Order
    extra_context = {
        'title': 'GeekShop - все заказы'
    }

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)


class OrderCreateView(LoginRequiredMixin, CreateView):
    model = Order
    fields = []
    success_url = reverse_lazy('ordersapp:list')
    extra_context = {
        'title': 'GeekShop - создание заказа'
    }
    formset = None
    OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm,
                                         formset=OrderInlineFormSet, extra=0)

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user, is_active=True)

    def get_context_data(self, **kwargs):
        return super(OrderCreateView, self).get_context_data(order_items=self.formset, **kwargs)

    def get(self, request, *args, **kwargs):
        baskets = Basket.objects.filter(user=request.user)
        if baskets:
            self.OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm,
                                                      formset=OrderInlineFormSet, extra=baskets.count())
            self.formset = self.OrderFormSet(
                initial=[{
                    'product_id': basket.product.pk,
                    'product_name': basket.product.name,
                    'quantity': basket.quantity,
                    'price': basket.total_price
                } for basket in baskets])
        else:
            self.formset = self.OrderFormSet()

        return super(OrderCreateView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.formset = self.OrderFormSet(request.POST)
        return super(OrderCreateView, self).post(request, *args, **kwargs)

    def form_valid(self, form):
        baskets = Basket.objects.filter(user=self.request.user)
        try:
            with transaction.atomic():
                form.instance.user = self.request.user
                form.instance.is_active = True
                if baskets:
                    baskets.delete()
                self.object = form.save()
                if self.formset.is_valid():
                    self.formset.instance = self.object
                    self.formset.save()
                if self.object.total_price == 0:
                    self.object.delete()
        except IntegrityError:
            return HttpResponseRedirect(reverse_lazy('ordersapp:create'))
        else:
            return super(OrderCreateView, self).form_valid(form)


class OrderUpdateView(LoginRequiredMixin, UpdateView):
    model = Order
    fields = []
    success_url = reverse_lazy('ordersapp:list')
    extra_context = {
        'title': 'GeekShop - редактирование заказа'
    }
    formset = None
    OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm,
                                         formset=OrderInlineFormSet, extra=0)

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user, is_active=True)

    def get_context_data(self, **kwargs):
        context = super(OrderUpdateView, self).get_context_data(**kwargs)
        context['order_items'] = self.formset
        return context

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.formset = self.OrderFormSet(instance=self.object)
        for form in self.formset:
            if form.instance.pk:
                form.initial['product_id'] = form.instance.product_id
                form.initial['product_name'] = form.instance.product.name
                form.initial['price'] = form.instance.total_price
        return super(OrderUpdateView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.formset = self.OrderFormSet(request.POST, instance=self.object)
        return super(OrderUpdateView, self).post(request, *args, **kwargs)

    def form_valid(self, form):
        context = self.get_context_data()
        order_items = context['order_items']
        try:
            with transaction.atomic():
                if order_items.is_valid():
                    order_items.instance = self.object
                    order_items.save()
                if self.object.total_price == 0:
                    self.object.delete()
        except IntegrityError:
            return HttpResponseRedirect(reverse_lazy('ordersapp:update', kwargs={'pk': self.kwargs.get('pk')}))
        else:
            return super(OrderUpdateView, self).form_valid(form)


class OrderDeleteView(LoginRequiredMixin, DeleteView):
    model = Order
    success_url = reverse_lazy('ordersapp:list')
    extra_context = {
        'title': 'GeekShop - удаление заказа'
    }


class OrderDetailView(LoginRequiredMixin, DetailView):
    model = Order
    extra_context = {
        'title': 'GeekShop - просмотр заказа'
    }


@login_required
def order_forming_complete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.SEND_TO_PROCEED
    order.save()
    return HttpResponseRedirect(reverse('ordersapp:list'))

ordersapp/templates/ordersapp/order_confirm_delete.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
<div class="text-center">
   <div class="category_delete">
       <div class="h1">Уверены, что хотите удалить?</div>
       {% include 'ordersapp/includes/inc_order_summary.html' %}
       <form action="{% url 'ordersapp:delete' object.pk %}" method="post">
           {% csrf_token %}
           <input class="btn btn-danger" type="submit" value="удалить">
       </form>
       <button class="btn btn-success mt-4">
           <a href="{% url 'ordersapp:list' %}">отмена</a>
       </button>
   </div>
</div>
{% endblock %}

ordersapp/templates/ordersapp/order_detail.html
{% extends "mainapp/base.html" %}
{% load static %}

{% block content %}
    <div class="container">
        {% include 'ordersapp/includes/inc_order_summary.html' %}
        <div class="basket_list">
            {% for item in object.order_items.select_related %}
                <div class="basket_record">
                    <img style="height: 150px" src="{{ item.product.image.url }}"
                         alt="{{ item.product.short_desc }}">
                    <span class="category_name">
                   {{ item.product.category.name }}
               </span>
                    <span class="product_name">{{ item.product.name }}</span>
                    <span class="product_price">
                   {{ item.product.price }}&nbsp;руб.
               </span>
                    <span class="product_quantity">
                   x {{ item.quantity }} шт.
               </span>
                    <span class="product_cost">
                    = {{ item.total_price }}&nbsp;руб.
               </span>
                </div>
            {% endfor %}
        </div>
        {% include 'ordersapp/includes/inc_order_actions.html' %}
    </div>
{% endblock %}

ordersapp/templates/ordersapp/order_form.html
{% extends "mainapp/base.html" %}
{% load static %}

{% block content %}
    <div class="container">
        {% include 'ordersapp/includes/inc_order_summary.html' %}
        <div class="order_form">
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <table class="table">
                    {{ order_items.management_form }}
                    {% for form in order_items.forms %}
                        {% if forloop.first %}
                            <thead>
                            <tr>
                                {% for field in form.visible_fields %}
                                    <th class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                                        {{ field.label|capfirst }}
                                    </th>
                                {% endfor %}
                            </tr>
                            </thead>
                        {% endif %}
                        <tr class="formset_row">
                            {% for field in form.visible_fields %}
                                <td class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                                    {% if forloop.first %}
                                        {% for hidden in form.hidden_fields %}
                                            {{ hidden }}
                                        {% endfor %}
                                    {% endif %}
                                    {{ field.errors.as_ul }}
                                    {% if field.name == 'price' %}
                                        {% if field.value %}
                                            <span class="order-items-{{ forloop.parentloop.counter0 }}-price">
                                            {{ field.value }}
                                        </span> руб.
                                        {% endif %}
                                    {% else %}
                                        {{ field }}
                                    {% endif %}
                                </td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                </table>
                <button type="submit" value="сохранить" class="btn btn-success btn-round form-control last mb-1">
                    сохранить
                </button>
                {% include 'ordersapp/includes/inc_order_actions.html' %}
            </form>
        </div>
    </div>
{% endblock %}

ordersapp/templates/ordersapp/order_list.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
    <div class="text-center">
        <div class="h2 text-center head">
            Ваши заказы,
            {% if user.first_name %}
                {{ user.first_name|title }}
            {% else %}
                Пользователь {{ user.username|title }}
            {% endif %}
        </div>
        <table class="table orders_list">
            <thead>
            <tr>
                <th>ID</th>
                <th>Создан</th>
                <th>Обновлен</th>
                <th>Статус</th>
            </tr>
            </thead>
            <tbody>
            {% for item in object_list %}
                {% if item.is_active %}
                    <tr>
                        <td class="td1 orders_list">{{ item.pk }}</td>
                        <td>{{ item.created_at|date:"Y-m-d H:i:s" }}</td>
                        <td>{{ item.updated_at|date:"Y-m-d H:i:s" }}</td>
                        <td>{{ item.get_status_display }}</td>
                        <td>
                            <a href="{% url 'ordersapp:read' item.pk %}">
                                посмотреть
                            </a>
                        </td>
                        <td>
                            {% if item.status == 'FM' %}
                                <a href="{% url 'ordersapp:update' item.pk %}">
                                    редактировать
                                </a>
                            {% endif %}
                        </td>
                        <td>
                            {% if item.status == 'FM' %}
                                <a href="{% url 'ordersapp:delete' item.pk %}">
                                    удалить
                                </a>
                            {% endif %}
                        </td>
                    </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>

        <a class="btn btn-light btn-round" href="{% url 'index' %}">
            на главную
        </a>
        <a class="btn btn-warning btn-round" href="{% url 'ordersapp:create' %}">
            новый
        </a>
    </div>
{% endblock %}